/* -------------------------------------------------------------------------
* Project     : CL-\ Violetta ex Anna ex NIC
* Description : Data Explorer
* Revision    : 0.021
* File        : type.js
* Function    : Types management
* FirstEdit   : 16/03/2022
* LastEdit    : 31/01/2026
* Author      : Luigi D. Capra
* Copyright(c): Luigi D. Capra 2017, 2026
* System      : Mozilla FireFox 80+
* License     : https://www.gnu.org/licenses/lgpl-3.0.txt
* -------------------------------------------------------------------------
*
* ### Needs
*     The DDJ-Program has been developed to display data collections generated by other programs (Native-Programs) for debug purposes.
*     If the Native-Program is a JS program the Collections could be passed directly to DDJ creating a CL_XDB class,
*     oterwise DDJ could acquire the Collections reading them from an external file or downloading from a website.
*     In any case we have to deal with multiple types:
*     Type_JS  = JavaScript's types.
*     Type_In  = type that could be specified as a value of HTML <input> "type" attribute.
*     Type_Out = type used to select display mode.
*     type     = user defined semantic-yypes (Type_Sem).
*
*     HTML+CSS+JS is very good for display purposes, but JavaScript is a loose type language that support a limited number of types, so exotic type must be mapped on the available types.
*     This imply a double mapping: for output on HTML's input-tag types (Type_Out) and for input on JS' types (Type_In).
*        
* ### Requirements
* ### Specifications
* ### Functional Requirements
* ### Non Functional Requirements
*     G_aFld_aFld1 defines the possible mapping of Native-Types on Type_Out and Type_In. 
*  
*/
"use strict";

/*----- Global Constants ---------------------------------------------*/

const C_jaType_szType_JS  = 0;      /* JS-Type. */
const C_jaType_szType_Anc = 1;      /* Ancestor-Type */
const C_jaType_szType_Out = 2;      /* Reference to HTML's elements or OLS' functions that should be used to display the value. */
const C_jaType_szType_In  = 3;      /* Reference to HTML's <input> Types. */
const C_jaType_iLenMax    = 4;
const C_jaType_szKnd      = 5;
const C_jaType_oAux       = 6;
const C_jaType_szNote     = 7;
const C_jaType_jSeq       = 8;

const C_iLen_Fld_Dflt     = 8;      /* Default field's length. */

/*----- Global Variables ---------------------------------------------*/

var G_oEnum_jFlag = {
"flag":     0
};

var G_oEnum_jBool = {
"false":    0,
"true":     1
};

var G_oEnum_jDate = {
"YYYYMMDD":  0,
"MMDDYYYY":  1,
"DDMMYYYY":  2
};

var G_oEnum_jWDay = {
"sunday":    0,
"monday":    1,
"tuesday":   2,
"wednesday": 3,
"thursday":  4,
"friday":    5,
"saturday":  6
};

var G_oEnum_jMonth = {
"January":   1,
"February":  2,
"March":     3,
"April":     4,
"May":       5,
"June":      6,
"July":      7,
"August":    8,
"September": 9,
"October":  10,
"November": 11,
"December": 12
};

var G_oEnum_jRel = {
"==": "==",
"!=": "!=",
"<":  "<", 
">":  ">", 
"<=": "<=",
">=": ">=",
};

var G_oEnum_jKndTup = {
"Null":  0,
"Arr":   1,
"Obj":   2, 
"aRcd":  3, 
"aObj":  4,
"asRcd": 5,
"asObj": 6
};

var G_oEnum_jConoscenze = {
" ": 0,
"4 Completa":  4,
"3 Adeguata":  3,
"2 Parziale":  2, 
"1 Scarsa":    1
};
var G_oEnum_jCompetenze = {
" ": 0,
"6 Completa":  6,
"5 Adeguata":  5,
"4 Accettab.": 4,
"3 Parziale":  3, 
"2 Scarsa":    2, 
"1 Nulla":     1
};
var G_oEnum_jSvolgimento  = {
" ": 0,
"3 Completa":  3,
"2 Adeguata":  2,
"1 Parziale":  1
};
var G_oEnum_jCorrettezza = {
" ": 0,
"4 Completa":  4,
"3 Adeguata":  3,
"2 Parziale":  2, 
"1 Scarsa":    1
};
var G_oEnum_jArgomentazione = {
" ": 0,
"3 Completa":  3,
"2 Parziale":  2, 
"1 Scarsa":    1
};

var G_oEnum_szNm_Coll = {
" ": 0,
"Remarks":      1,
"Directories":  2, 
"Files":        3,
"Alt-Remarks":  4,
"Finance":      5
};

var G_oEnum_Type = {
}
/* 
* Data Layout of the "Data Layout" that is the aFld data structure (see: XDB0).
*/
var G_aFld_aFld = [
  {"szNm":"szNm",      "szType":"string",   "iLen":5, "szRem":"Name of the field."},
  {"szNm":"szType",    "szType":"jLst_Type","iLen":5, "szRem":"Type_Sem of the Field."},
  {"szNm":"iLen",      "szType":"int",      "iLen":5, "szRem":"Number of chars reserved for the field."},
  {"szNm":"szRem",     "szType":"string",   "iLen":5, "szRem":"Description."}
];
/* 
* Data Layout of the UsrView's "Data Layout" that is the aFld1 data structure (see: UsrView0).
*/
var G_aFld_aFld1 = [
  {"szNm":"iPos0",     "szType":"number",   "iLen":3, "szRem":"Position of the field in the Original Layout (aFld0)", "fReadOnly":true},  /* RO Position of the field in the original Layout (aFld) */
  {"szNm":"iPos1",     "szType":"number",   "iLen":3, "szRem":"Position of the field in the UsrView Layout (aFld1)"},  /* RW Position of the field in the UsrView Layout (aFld1) */
  {"szNm":"fVisible",  "szType":"Flag",     "iLen":3, "szRem":"Flag: Show the field/column"},
  {"szNm":"szNm",      "szType":"string",   "iLen":8, "szRem":"Name of the field", "fRO":true},                        /* RO Name of the field */
  {"szNm":"szCaption", "szType":"string",   "iLen":8, "szRem":"Name showed"},                                          /* RW Name showed */
  {"szNm":"szType",    "szType":"jLst_Type","iLen":4, "szRem":"Semantic type of the field"},                           /* RW Type_Sem of the Field */
  {"szNm":"iLen",      "szType":"int",      "iLen":3, "szRem":"Size of the field"},                                    /* RW Number of chars reserved for the field */
  {"szNm":"Aux0",      "szType":"object",   "iLen":3, "szRem":""},                                                     /* Ex. "Aux0":{"F_fChk":U_Null, "Min":1, "Max":100,"szShow":"","oEnum":"", "iCard":"", "F_Val_PreProc":U_Null, "F_Val_PostProc":U_Null} */
  {"szNm":"fReadOnly", "szType":"Flag",     "iLen":3, "szRem":"Flag: Field set Read Only"},                            /* RW field Read Only */
  {"szNm":"fCaseSens", "szType":"Flag",     "iLen":3, "szRem":"Flag: Case Sensitive sorting"},                         /* RW Case Sensitive Sorting */
  {"szNm":"fRecalc",   "szType":"Flag",     "iLen":3, "szRem":"Flag. Enables automatic recalc of field values"},       /* RW enables automatic recalculation of field values */
  {"szNm":"szCode",    "szType":"string",   "iLen":3, "szRem":"JS expression used for recalc."},                       /* RW code that defines the new value ex. "$[5] * 2". NOTE: values will be calculated una tantum. */
  {"szNm":"szRem",     "szType":"string",   "iLen":10,"szRem":"Remarks"},                                              /* RW Remarks */

  {"fVisible":false,"szNm":"szTBM_Table",  "szType":"none", "iLen":0, "szRem":"SetPar", "szCode":"Layout"},            /* Select Layout TBM. */
  {"fVisible":false,"szNm":"szTBM_PopUp",  "szType":"none", "iLen":0, "szRem":"SetPar", "szCode":"PopUp_Layout"},      /* Select Layout TBM. */
  {"fVisible":false,"szNm":"szHelp_Table", "szType":"none", "iLen":0, "szRem":"SetPar", "szCode":"std/afld1"}          /* Select Layout Help file. */
];
/*
* XDB0 Layout.
*/
var G_aFld_XDB0 = [
{"szNm":"F_Tup_New",   "szType":"function","iLen":5,"szRem":"Create a new, empty, Tuple"},
{"szNm":"U_Sort",      "szType":"function","iLen":5,"szRem":"Sort function"},

{"szNm":"_szNmClass",  "szType":"string",  "iLen":5,"szRem":"Object Class."},
{"szNm":"JKndTup0",    "szType":"number",  "iLen":5,"szRem":"Format Kind."},
{"szNm":"szJKndTup0",  "szType":"string",  "iLen":5,"szRem":"Format Kind."},
{"szNm":"szNmColl",    "szType":"string",  "iLen":5,"szRem":"Name of the Collection."},
{"szNm":"szNm_URL",    "szType":"string",  "iLen":5,"szRem":"Source File."},
{"szNm":"aFld0",       "szType":"object",  "iLen":5,"szRem":"Physical Collection Layout."},
{"szNm":"szNm_aFld",   "szType":"string",  "iLen":5,"szRem":"Name of the Layout."},
{"szNm":"XDB_aFld",    "szType":"object",  "iLen":5,"szRem":"Collection's Layout"},
{"szNm":"Coll0",       "szType":"object",  "iLen":5,"szRem":"Collection."},
{"szNm":"Coll_Bak",    "szType":"object",  "iLen":5,"szRem":"Collection BackUp."},
{"szNm":"szNote",      "szType":"string",  "iLen":5,"szRem":"Description."},
{"szNm":"jPrimKey",    "szType":"string",  "iLen":5,"szRem":"Primary key."},
{"szNm":"Tup_Sel",     "szType":"object",  "iLen":5,"szRem":"Tuple currently selected."},
{"szNm":"Tup_Copy",    "szType":"object",  "iLen":5,"szRem":"Copy buffer."},
{"szNm":"Tup_Filter",  "szType":"object",  "iLen":5,"szRem":"Filter buffer."},
{"szNm":"jCd_Def",     "szType":"number",  "iLen":5,"szRem":"Module in which the collection was defined."},
{"szNm":"jCnf",        "szType":"number",  "iLen":5,"szRem":"Degree of confidentiality"},
{"szNm":"fReadOnly",   "szType":"number",  "iLen":5,"szRem":"Flag: Read Only."},
{"szNm":"fMng_Undef",  "szType":"boolean", "iLen":5,"szRem":"Flag: Manage Undefined Fields"},
{"szNm":"fLive",       "szType":"boolean", "iLen":5,"szRem":"Flag: Collection which value could change at runtime."},
{"szNm":"fService",    "szType":"boolean", "iLen":5,"szRem":"Flag: fields descriptor."},
{"szNm":"faFld",       "szType":"boolean", "iLen":5,"szRem":"Flag: Collection layout."},
{"szNm":"_Hdr0_",      "szType":"object",  "iLen":5,"szRem":"Preserve OLS' Header"},
{"szNm":"OLS_Ld",      "szType":"object",  "iLen":5,"szRem":"Preserve OLS object loaded."},

{"fVisible":false,"szNm":"szHelp_Table", "szType":"none", "iLen":0, "szRem":"SetPar", "szCode":"xdb"}      /* Select XDB Help file. */
];

/*
* UsrView Layout.
*/
var G_aFld_UsrView = [
{"szNm":"_szNmClass", "szType":"string","iLen":5,"szRem":"Obj Class."},
{"szNm":"F_Arr_Mp_Field", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_TupNull", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_aNdx", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_aNdx_Make", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_asKey_Make", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_jaFld1_Sel", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_jaNdx_Sel", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_szHTML_OpenCard", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_szKey_Sort", "szType":"function","iLen":5,"szRem":""},
{"szNm":"F_KeyTup_Sel", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Clear_Filter", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_ConfirmCard", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_DBMS", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Delete", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Insert", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Invert_Filter", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Pre_Select", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Prn_Elem", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Reset_aNdx", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_SaveChange", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Sel_Pg", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Set_Field", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Toggle_Filter", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Upd_Elem", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Upd_aNdx", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Upd_asKey", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_Update", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_XShow_CR", "szType":"function","iLen":5,"szRem":""},
{"szNm":"U_XShow_RC", "szType":"function","iLen":5,"szRem":""},

{"szNm":"ElemPrv", "szType":"string","iLen":5,"szRem":""},
{"szNm":"Fld_Sel", "szType":"string","iLen":5,"szRem":""},
{"szNm":"Key_Fld", "szType":"string","iLen":5,"szRem":""},
{"szNm":"Val_Sel", "szType":"string","iLen":5,"szRem":"Value of the field currently selected."},
{"szNm":"XDB0", "szType":"string","iLen":5,"szRem":"Physical Collection metadata."},
{"szNm":"aFld1", "szType":"string","iLen":5,"szRem":"User View Layout. Array of Fields showed in the User View."},
{"szNm":"aNdx", "szType":"string","iLen":5,"szRem":"Index of the whole Collection."},
{"szNm":"aNdxFlt_F", "szType":"string","iLen":5,"szRem":"Index of Tuples that do not match Filter conditions."},
{"szNm":"aNdxFlt_GT", "szType":"string","iLen":5,"szRem":"Index of Tuples matching GoTo conditions."},
{"szNm":"aNdxFlt_T", "szType":"string","iLen":5,"szRem":"Index of Tuples matching Filter conditions."},
{"szNm":"aiPos", "szType":"string","iLen":5,"szRem":"List of the positions of the visible fields. (Ref. iPos0)."},
{"szNm":"asKey", "szType":"string","iLen":5,"szRem":"Array used to speed up access using the key."},
{"szNm":"fAsc", "szType":"string","iLen":5,"szRem":""},
{"szNm":"fCaption", "szType":"string","iLen":5,"szRem":""},
{"szNm":"fFlt", "szType":"string","iLen":5,"szRem":""},
{"szNm":"fInv", "szType":"string","iLen":5,"szRem":""},
{"szNm":"fJoin", "szType":"string","iLen":5,"szRem":""},
{"szNm":"fPrdRefr", "szType":"string","iLen":5,"szRem":""},
{"szNm":"fRC", "szType":"string","iLen":5,"szRem":""},
{"szNm":"fReadOnly", "szType":"string","iLen":5,"szRem":"Collection Read Only vs. Read Write."},
{"szNm":"fSave_AutoExec", "szType":"string","iLen":5,"szRem":""},
{"szNm":"fSet_Field", "szType":"string","iLen":5,"szRem":""},
{"szNm":"iCnt_Filter", "szType":"string","iLen":5,"szRem":""},
{"szNm":"iCol_Item_Sel", "szType":"string","iLen":5,"szRem":""},
{"szNm":"iCol_Sort", "szType":"string","iLen":5,"szRem":""},
{"szNm":"iHgt", "szType":"string","iLen":5,"szRem":""},
{"szNm":"iRow_Item_Sel", "szType":"string","iLen":5,"szRem":""},
{"szNm":"iStart", "szType":"string","iLen":5,"szRem":""},
{"szNm":"iStop", "szType":"string","iLen":5,"szRem":""},
{"szNm":"iWdt", "szType":"string","iLen":5,"szRem":""},
{"szNm":"jNdxFlt_GT", "szType":"number","iLen":5,"szRem":""},
{"szNm":"jPg", "szType":"number","iLen":5,"szRem":""},
{"szNm":"jXFst", "szType":"number","iLen":5,"szRem":""},
{"szNm":"jYFst", "szType":"number","iLen":5,"szRem":""},
{"szNm":"jaFld1", "szType":"number","iLen":5,"szRem":"Position of the descriptor corresponding to the selected field in aFld1."},
{"szNm":"jaFld1_aNdx", "szType":"number","iLen":5,"szRem":""},
{"szNm":"jaNdx_Sel", "szType":"number","iLen":5,"szRem":""},
{"szNm":"pF_fFilter", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szAS", "szType":"string","iLen":5,"szRem":"Char used as Alias."},
{"szNm":"szCond", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szHelp_Table", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szId_Div", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szId_Tbl", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szId_Tbl_B", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szId_Tbl_Card", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szId_Tbl_H", "szType":"string","iLen":5,"szRem":""},
{"szNm":"KeyTup", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szNmColl", "szType":"string","iLen":5,"szRem":"Collection name."},
{"szNm":"szNote", "szType":"string","iLen":5,"szRem":"Notes"},
{"szNm":"szTBM_Card", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szTBM_PopUp", "szType":"string","iLen":5,"szRem":""},
{"szNm":"szTBM_Table", "szType":"string","iLen":5,"szRem":""},
{"fVisible":false,"szNm":"szHelp_Table", "szType":"none", "iLen":0, "szRem":"SetPar", "szCode":"usrview"}      /* Select UsrView Help file. */
];
/* 
* Data Layout of the Statistics data structure.
*/
var G_aFld_Stat = [
{"szNm":"Field Num.","szType":"number","iLen":8,"szRem":""},
{"szNm":"Field Name","szType":"string","iLen":8,"szRem":""},
{"szNm":"Type","szType":"string","iLen":8,"szRem":""},
{"szNm":"Type_JS","szType":"string","iLen":8,"szRem":""},
{"szNm":"Num. of Data","szType":"number","iLen":8,"szRem":""},
{"szNm":"Valid Data","szType":"number","iLen":8,"szRem":""},
{"szNm":"Sum","szType":"number","iLen":8,"szRem":""},
{"szNm":"Number of Classes","szType":"number","iLen":8,"szRem":""},
{"szNm":"Min","szType":"number","iLen":8,"szRem":""},
{"szNm":"Max","szType":"number","iLen":8,"szRem":""},
{"szNm":"Average","szType":"number","iLen":8,"szRem":""},
{"szNm":"Median","szType":"number","iLen":8,"szRem":""},
{"szNm":"Mode","szType":"number","iLen":8,"szRem":""},
{"szNm":"MultiModal","szType":"boolean","iLen":8,"szRem":""},
{"szNm":"Frequency of the Mode","szType":"number","iLen":8,"szRem":""},
{"szNm":"Number of Distinct values","szType":"number","iLen":8,"szRem":""},
{"szNm":"1-Quart","szType":"number","iLen":8,"szRem":""},
{"szNm":"3-Quart","szType":"number","iLen":8,"szRem":""},

{"szNm":"Mean","szType":"number","iLen":8,"szRem":""},
{"szNm":"Variance","szType":"number","iLen":8,"szRem":""},
{"szNm":"Standard Deviation","szType":"number","iLen":8,"szRem":""},
{"szNm":"Rel. Disp","szType":"number","iLen":8,"szRem":""},
{"szNm":"Variance Corrected","szType":"number","iLen":8,"szRem":""},
{"szNm":"Standard Deviation Corrected","szType":"number","iLen":8,"szRem":""},
{"szNm":"Skew","szType":"number","iLen":8,"szRem":""},
{"szNm":"Kurtosis","szType":"number","iLen":8,"szRem":""},
{"szNm":"Width Min","szType":"number","iLen":8,"szRem":""},
{"szNm":"Width Max","szType":"number","iLen":8,"szRem":""},
{"szNm":"Width (Trimmed) Min","szType":"number","iLen":8,"szRem":""},
{"szNm":"Width (Trimmed) Max","szType":"number","iLen":8,"szRem":""},
{"szNm":"Num. of Errors","szType":"number","iLen":8,"szRem":""},
{"szNm":"Num. Undefined","szType":"number","iLen":8,"szRem":""},
{"szNm":"Num. Null","szType":"number","iLen":8,"szRem":""},
{"szNm":"Num. NaN","szType":"number","iLen":8,"szRem":""}
];
/* 
* Data Layout of the Log data structure.
*/
var G_aFld_Log = [
  {"szNm":"is_Ela",   "szType":"number",   "iLen":5, "szRem":"Seconds elapsed since the program start."},
  {"szNm":"jCd",      "szType":"number",   "iLen":5, "szRem":"Code of the Module."},
  {"szNm":"jReg",     "szType":"number",   "iLen":5, "szRem":"Recording point."},
  {"szNm":"jLvl",     "szType":"number",   "iLen":5, "szRem":"Level of Significance."},  /* $CONSTRAINT: const C_jPos_jLvl = 3; */
  {"szNm":"Kind",     "szType":"string",   "iLen":10, "szRem":"Category."},
  {"szNm":"Message",  "szType":"string",   "iLen":25, "szRem":"Remarks."},
  
  {"fVisible":false,"szNm":"szTBM_Table", "szType":"none", "iLen":0, "szRem":"SetPar", "szCode":"Log"}
];
/* 
* Layout of a generic Array.
*/
var G_aFld_Arr0 = [
  {"szNm":"Value",     "szType":"string",  "iLen":5, "szCaption":"Value", "iPos0":0, "iPos1":0, "fVisible":true}
];
/* 
* Layout of a generic Object.
*/
var G_aFld_Obj0 = [
  {"szNm":"Attribute", "szType":"string",  "iLen":4, "szCaption":"Attribute", "iPos0":0, "iPos1":0, "fVisible":true},
  {"szNm":"Value",     "szType":"string",  "iLen":8, "szCaption":"Value",     "iPos0":1, "iPos1":1, "fVisible":true}
];
/* 
* Layout of Function tables.
*/
var G_aFld_Func = [
  {"szNm":"x",    "szType":"number",  "iLen":5, "szCode":"(i)", "szRem":"x"},
  {"szNm":"y",    "szType":"number",  "iLen":5, "szCode":"(i**2 + 3*i + 5)", "szRem":"y=f(x)"}
];
/* 
* Layout of array of absolute frequencies
*/
var G_aFld_aAbsFreq = [
  {"szNm":"Xj",   "szType":"number", "iLen":5, "szRem":"Center of the class 'j'."},
  {"szNm":"Freq", "szType":"number", "iLen":5, "szRem":"Absolute frequency."}
];
/* 
* Layout of the list of the AS
*/
var G_aFld_AS = [
  {"szNm":"szAS",     "szType":"string",  "iLen":5, "szRem":""},
  {"szNm":"szNmColl", "szType":"string",  "iLen":5, "szRem":""}
];
/* 
* Layout of Year
*/
var G_aFld_Year = [
  {"szNm":"Year",    "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"IncWeek", "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"Easter",  "szType":"date",    "iLen":5, "szRem":""},
  {"szNm":"Carnival","szType":"date",    "iLen":5, "szRem":""}
];
/* 
* Layout of Calendar
*/
var G_aFld_Calendar = [
  {"szNm":"Year",    "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"IncWeek", "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"Easter",  "szType":"date",    "iLen":5, "szRem":""},
  {"szNm":"Carnival","szType":"date",    "iLen":5, "szRem":""}
];
/* 
* Layout of RcdDay
*/
var G_aFld_RcdDay = [
  {"szNm":"Date",    "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"Year",    "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"Month",   "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"Day",     "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"szWDay",  "szType":"string",  "iLen":5, "szRem":""},
  {"szNm":"iYDay",   "szType":"number",  "iLen":5, "szRem":""},
  {"szNm":"iYWeek",  "szType":"number",  "iLen":5, "szRem":""}
];
/* 
* Types' descriptors Layout.
*/
var G_aFld_Type = [
  {"szNm":"szNmType",    "szType":"string",    "iLen":5, "szRem":"Semantic Type."}, 
  {"szNm":"szType_JS",   "szType":"Type",      "iLen":5, "szRem":"JS-Type."},
  {"szNm":"szType_Anc",  "szType":"Type",      "iLen":5, "szRem":"Ancestor-Type."},
  {"szNm":"szType_Out",  "szType":"jLst_Type", "iLen":5, "szRem":"Output format."},
  {"szNm":"szType_In",   "szType":"Type_JS",   "iLen":5, "szRem":"HTML+ <input> Type."},
  {"szNm":"iLenMax",     "szType":"number",    "iLen":5, "szRem":"Number of chars required to display the value."},
  {"szNm":"szOrg",       "szType":"string",    "iLen":5, "szRem":"Origin of the Type."},
  {"szNm":"oAux",        "szType":"object",    "iLen":5, "szRem":"Auxiliary info"}, 
  {"szNm":"szNote",      "szType":"string",    "iLen":10,"szRem":"Description of the Type."}, 
  {"szNm":"jSeq",        "szType":"number",    "iLen":5, "szRem":""}
];
/*
* Set of values returned by typeof(). JavaScript's native data types.
* Layout: aFld_Type
*/
/*
* Set of values returned by typeof(). JavaScript's native data types.
*/
var G_asRcd_Type_JS = {
"string":    ["string",   "string",   "string",    "string",  8, "JS", {"get":"getString"}, "JS' text.", 1],
"number":    ["number",   "number",   "number",    "number",  8, "JS", {"CPU":true, "default":0}, "JS' number.", 2],
"boolean":   ["boolean",  "boolean",  "boolean",   "boolean", 8, "JS", {"Min":false, "Max":true, "default":false}, "JS' boolean.", 3],
"object":    ["object",   "object",   "object",    "string",  8, "JS", {"default":{}},    "JS' object.", 4],
"function":  ["function", "function", "function",  "string",  8, "JS", {}, "JS' function.", 5],
"bigint":    ["bigint",   "bigint",   "bigint",    "number",  8, "JS", {"CPU":true, "Min":-0x8000000000000000, "Max":0x7fffffffffffffff, "default":0}, "JS' bigint.", 6],
"symbol":    ["symbol",   "symbol",   "symbol",    "string",  8, "JS", {}, "JS' symbol.", 7],
"undefined": ["undefined","undefined","undefined", "string",  8, "JS", {}, "JS' 'undefined' type. This type is used internally by programs to indicates value not initialized. Do not use it!", 0]
}; /* G_asRcd_Type_JS */

// label                               /* Semantic Type */
// const C_jaType_szType_JS  = 0;      /* JS-Type. */
// const C_jaType_szType_Anc = 1;      /* Ancestor-Type */
// const C_jaType_szType_Out = 2;      /* Reference to HTML's elements tha should be used to display the value. */
// const C_jaType_szType_In  = 3;      /* Reference to HTML's <input> Types. */
// const C_jaType_iLenMax    = 4;
// const C_jaType_szKnd      = 5;
// const C_jaType_oAux       = 6;
// const C_jaType_szNote     = 7;
// const C_jaType_jSeq       = 8;
/*
* Tables defining type's gerarchy.
*/
var G_asRcd_Type = {
"string":    ["string",   "string",   "string",    "string",  8, "JS", {"get":"getString"}, "JS' text.", 1],
"number":    ["number",   "number",   "number",    "number",  8, "JS", {"CPU":true, "default":0}, "JS' number.", 2],
"boolean":   ["boolean",  "boolean",  "boolean",   "boolean", 8, "JS", {"Min":false, "Max":true, "default":false}, "JS' boolean.", 3],
"object":    ["object",   "object",   "object",    "string",  8, "JS", {"default":{}},    "JS' object.", 4],
"function":  ["function", "function", "function",  "string",  8, "JS", {}, "JS' function.", 5],
"bigint":    ["bigint",   "bigint",   "bigint",    "bigint",  8, "JS", {"CPU":true, "Min":-0x8000000000000000, "Max":0x7fffffffffffffff, "default":0}, "JS' bigint.", 6],
"symbol":    ["symbol",   "symbol",   "symbol",    "string",  8, "JS", {}, "JS' symbol.", 7],
"undefined": ["undefined","undefined","undefined", "string",  8, "JS", {}, "JS' 'undefined' type. This type is used internally by programs to indicates value not initialized. Do not use it!", 0],

/*
* HTML's <input> types.
*/
"button":    ["no_type", "no_type",  "button",    "Flag",    8, "Input", {}, "Generic Button (trigger a function)",8],
"color":     ["string",  "color",    "color",     "color",   8, "Input", {"Min":"#000", "Max":"#fff", "default":"#000"}, "Color",9],
"date":      ["string",  "date",     "date",      "date",    8, "Input", {"get":"getDate", "default":"1970-01-01"}, "Date in YYYY-MM-DD format.",10],
"datetime":  ["string",  "datetime", "datetime",  "datetime",8, "Input", {}, "Date in YYYY-MM-DDThh:mm:ss.mmm+hh:mm format.",11],
"datetime-local": ["string",  "datetime-local", "datetime-local",  "datetime-local", 8, "Input", {"default":"1970-01-01T00:00"}, "Date in ISO format. Ex. 2018-06-12T19:30", 12],
"time":      ["string",  "time",     "time",      "string",  8, "Input", {"default":"00:00:00"}, "time in hh:mm:ss.mmm format.", 13],
"month":     ["string",  "month",    "month",     "month",   8, "Input", {"F_fChk":F_fChk_Month}, "Month of the year.  E.g. '2018-06'", 14],
"week":      ["string",  "week",     "week",      "week",    8, "Input", {"F_fChk":F_fChk_Week}, "Week of the year. E.g. '2018-W26'", 15],

"email":     ["string",  "email",    "email",     "string",  8, "Input", {}, "email", 16],
"tel":       ["string",  "tel",      "tel",       "string",  8, "Input", {}, "telephone number", 17],
"file":      ["string",  "file",     "file",      "string",  8, "Input", {}, "file - Ex. C:/documents/user/test.doc", 18],  /* Open using OLS */
"url":       ["string",  "url",      "url",       "string",  8, "Input", {}, "Generic URL. Ex. http.//www.google.com", 19], /* Open using OLS */
"image":     ["no_type", "no_type",  "none",      "none",    8, "Input", {}, "Image used as a button's caption.", 20],      /* HTML <input> Type. Dont'use type "image" use type "Image". */

"password":  ["string",  "password", "password",  "string",  8, "Input", {}, "password", 21],
"range":     ["number",  "number",   "range",     "range",   8, "Input", {}, "Range input type", 22],
"search":    ["no_type", "no_type",  "search",    "none",    8, "Input", {}, "Search", 23],
"reset":     ["no_type", "no_type",  "reset",     "none",    8, "Input", {}, "Reset Button", 24],
"submit":    ["no_type", "no_type",  "submit",    "none",    8, "Input", {}, "Submit Button", 25],
"select":    ["no_type", "no_type",  "select",    "string",  8, "Input+", {}, "Select", 26],

"hidden":    ["no_type", "no_type",  "hidden",    "none",    8, "Input", {}, "hidden", 27],
"text":      ["string",  "string",   "string",    "string",  8, "Input", {"get":"getString", "default":""}, "HTML's text == JS' string.", 28],

"textarea":  ["string",  "string",   "textarea",  "string",  8, "Input+", {"default":""}, "HTML text. Lines end with '<br>'.", 29],
"HTML":      ["string",  "string",   "HTML",      "HTML",    8, "Input+", {"get":"getString", "Min":"", "default":""}, "HTML text.", 30],
"MarkDown":  ["string",  "string",   "MarkDown",  "MarkDown",8, "Input+", {"get":"getString", "Min":"", "default":""}, "MarkDown text.", 31],


"SByte":     ["number",  "int",      "number",    "number",  8, "CPU", {"get":"getUInt8",  "CPU":true, "Min":-128, "Max":127, "default":0},  "signed 8 bits number.", 32],
"short":     ["number",  "int",      "number",    "number",  8, "CPU", {"get":"getUInt16", "CPU":true, "Min":-32768, "Max":32767, "default":0}, "signed 16 bits number.", 33],
"int":       ["number",  "int",      "number",    "number",  8, "CPU", {"get":"getUInt32", "CPU":true, "Min":-0x80000000, "Max":0x7fffffff, "default":0}, "signed 32 bits number.", 34],
"int64":     ["number",  "bigint",   "bigint",    "bigint",  8, "CPU", {"get":"getUInt64", "CPU":true, "Min":-0x8000000000000000, "Max":0x7fffffffffffffff, "default":0},"signed 64 bits number.", 35],

"Byte":      ["number",  "int",      "number",    "number",  8, "CPU", {"get":"getUInt8",  "CPU":true, "Min":0, "Max":255, "default":0}, "unsigned 8 bits number.", 36],
"Word":      ["number",  "int",      "number",    "number",  8, "CPU", {"get":"getUInt16", "CPU":true, "Min":0, "Max":65535, "default":0}, "unsigned 16 bits number.", 38],
"DWord":     ["number",  "int",      "number",    "number",  8, "CPU", {"get":"getInt32",  "CPU":true, "Min":0, "Max":0x80000000, "default":0}, "unsigned 32 bits number.", 39],
"QWord":     ["number",  "bigint",   "number",    "number",  8, "CPU", {"get":"getInt64",  "CPU":true, "Min":0, "Max":0x8000000000000000, "default":0}, "unsigned 64 bits number.", 40],

"float":     ["number",  "real",     "number",    "number",  8, "CPU", {"get":"getFloat32","CPU":true, "Min":-Number.MAX_VALUE, "Max":Number.MAX_VALUE, "default":0}, "float number.", 41],
"real":      ["number",  "real",     "real",      "number",  8, "CPU", {"get":"getFloa64", "CPU":true, "Min":-Number.MAX_VALUE, "Max":Number.MAX_VALUE, "default":0}, "double number. Ex. 123.45 ", 42],
"adr":       ["number",  "bigint",   "number",    "number",  8, "CPU", {"get":"getFloa64", "CPU":true, "Min":-Number.MAX_VALUE, "Max":Number.MAX_VALUE, "default":0}, "64 bits address", 43],

"output":    ["output",  "output",   "output",    "output",  8, "output", {}, "output.", 98],
"Custom":    ["Custom",  "Custom",   "Custom",    "Custom",  8, "Custom", {}, "Custom data type.", 99],

"rExp":      ["number",  "real",     "rExp",      "number",  8, "POSIX", {}, "Real number. Ex. 1.2345e-5 "],

"hex":       ["number",  "DWord",    "hex",       "number",  8, "POSIX", {}, "Hexadecimal number Ex. 0x5a3b "],
"oct":       ["number",  "DWord",    "oct",       "number",  8, "POSIX", {}, "Octal number. Ex 0o7346 "],
"bin":       ["number",  "DWord",    "bin",       "number",  8, "POSIX", {}, "Binary number. Ex 0b10101101 "],

"AbsFreq":   ["number",  "number",   "number",    "number",  8, "Stat", {}, "Absolute frequency "],
"timestamp": ["number",  "bigint",   "timestamp", "timestamp",  8, "CPU", {}, "Number of milliseconds elapsed since January 1, 1970"],

"Type_JS":   ["string",  "string",   "string",    "string",  8, "DDJ", {}, "JS' Type"],
"Type":      ["string",  "string",   "string",    "string",  8, "DDJ", {}, "Type"],

//"Field":     ["string",  "no_type", "Field",    "enum", 8, "", {}, ""],      /* Field-Name */ 
//"Relation":  ["string",  "no_type", "Relation", "enum", 8, "", {}, ""],      /* Relation kind */ 

"link":      ["string",  "string",   "link",      "string",  8, "XType", {}, "HTML Link."],               /* Open using the Browser */
"SVG":       ["string",  "string",   "SVG",       "string",  8, "XType", {}, ""],
"TAG":       ["number",  "DWord",    "hex",       "number",  8, "DDJ", {}, "Tag codeword. Ex. 0x5a3b "],

/* File documents */

"Image":     ["string",  "string",   "Image",     "string",  8, "Res", {}, "URL of an external Image resource."],
"Audio":     ["string",  "string",   "Audio",     "string",  8, "Res", {}, "URL of an external Audio resource"],
"Video":     ["string",  "string",   "Video",     "string",  8, "Res", {}, "URL of an external Video resource"],
"Txt":       ["string",  "string",   "Txt",       "string",  8, "Res", {}, "URL of an external file of text. Open in the browser."],
"Doc":       ["string",  "string",   "Doc",       "string",  8, "Res", {}, "URL of an external document file (.DOC, .ODT or similar). Open in the browser."],
"html":      ["string",  "string",   "html",      "string",  8, "Res", {}, "URL of an external file in HTML format. Open in the browser. "],
"Icon":      ["string",  "string",   "Icon",      "string",  8, "Res", {}, "Icon's URL."],

"GPS":       ["string",  "string",   "GPS",       "string",  8, "XType", {}, "GPS coordinates. Latitude, Longitude. ex. 45.31, 7.98 "],
"PATH":      ["string",  "string",   "PATH",      "string",  8, "Res", {}, "File or directory's PATH."],  /* Open using OLS */
"memo":      ["string",  "string",   "memo",      "string",  8, "XType", {}, "DBIII memo."],

"Array":     ["string",  "Array",    "Array",     "string",  8, "CType", {}, "JS' array."],
"none":      ["no_type", "none",     "none",      "none",    8, "DDJ", {}, "Null Type."],

"Flag":      ["boolean", "Flag",     "Flag",      "Flag",    8, "CType", {}, "Single checkbox input type"],
"checkbox":  ["boolean", "checkbox", "checkbox",  "checkbox",8, "Input", {}, "checkbox input type"],
"radio":     ["number",  "radio",    "radio",     "radio",   8, "Input", {}, "Radio input type"],
"List":      ["number",  "List",     "List",      "List",    8, "Input+", {}, "List input type"],

"enum":      ["number",  "enum",     "enum",      "enum",    8, "CType", {}, "Set of alternative values defined by enumeration."],
"set":       ["number",  "set",      "set",       "set",     8, "CType", {}, "Set of value mapped on the bits of a Data Word."],

"HChkBox":   ["number",  "checkbox", "checkbox",  "checkbox", 8, "ChkBox", {}, "Horizontal checkbox"],
"NChkBox":   ["number",  "checkbox", "checkbox",  "checkbox", 8, "ChkBox", {}, "Horizontal checkbox, no caption"],

"HRadio":    ["number",  "radio",    "radio",     "radio",   8, "Radio", {}, "Horizontal radio-button"],
"NRadio":    ["number",  "radio",    "radio",     "radio",   8, "Radio", {}, "Horizontal radio-button, no caption"],

"jRB_WDay":  ["number",  "enum",     "radio",     "radio",   8, "RSet", {"szShow": "HRadio", "oEnum":G_oEnum_jWDay,  "iCard":7},  "Shows week-days radio buttons"],
"jRB_Month": ["number",  "enum",     "radio",     "radio",   8, "RSet", {"szShow": "radio",  "oEnum":G_oEnum_jMonth, "iCard":12}, "Shows months radio buttons"],
"jCB_WDay":  ["number",  "set",      "checkbox",  "checkbox",8, "CSet", {"szShow": "chkbox", "oEnum":G_oEnum_jWDay,  "iCard":7},  "Shows week-days checkbox"],
"jCB_Flag":  ["number",  "set",      "checkbox",  "checkbox",8, "CSet", {"szShow": "chkbox", "oEnum":G_oEnum_jFlag,  "iCard":2},  "Shows false/true checkbox"],
"jLst_Bool": ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jBool,  "iCard":2},  "Shows false/true list"],
"jLst_Date": ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jDate,  "iCard":3},  "Shows data-kinds list"],
"jLst_WDay": ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jWDay,  "iCard":7},  "Shows week-days list"],

"jLst_Rel":  ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jRel,   "iCard":6},  "Shows relations kind list"],
"jLst_Type": ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_Type,   "iCard":64}, "Shows Types list"],

"jLst_Conoscenze":   ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jConoscenze,    "iCard":64}, "Conoscenze"],
"jLst_Competenze":   ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jCompetenze,    "iCard":64}, "Competenze"],
"jLst_Svolgimento":  ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jSvolgimento,   "iCard":64}, "Svolgimento"],
"jLst_Correttezza":  ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jCorrettezza,   "iCard":64}, "Correttezza"],
"jLst_Argomentaz":   ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jArgomentazione,"iCard":64}, "Argomentazione"],

"jLst_szNm_Coll":    ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_szNm_Coll,      "iCard":64}, "Collezioni di annotazioni"],

"jLst_JKndTup":      ["number",  "enum",     "List",      "List",    8, "LSet", {"szShow": "list",   "oEnum":G_oEnum_jKndTup,"iCard":7},  "JKndTup"] 

}; /* G_asRcd_Type */

/* FlDsc - Files Descriptors. */

var G_aFld_FlDsc = [                                                            /* File/Directory descriptors returned by 'dir2.php' */
  {"szNm":"FileName",  "szType":"PATH",   "iLen":12, "szRem":"File name.", "fCaseSens":false},
  {"szNm":"Extension", "szType":"string", "iLen":4,  "szRem":"File extension."},
  {"szNm":"Size",      "szType":"number", "iLen":6,  "szRem":"File size."},
  {"szNm":"Modified",  "szType":"string", "iLen":6,  "szRem":"Date."},
  {"szNm":"Permis",    "szType":"hex",    "iLen":4,  "szRem":"Attributes."},
  {"szNm":"Type",      "szType":"number", "iLen":4,  "szRem":"Type."},
  {"szNm":"Icon",      "szType":"Icon",   "iLen":3,  "szRem":"Icon."},   
  {"szNm":"Preview",   "szType":"Image",  "iLen":12, "szRem":"Preview."},
  {"szNm":"Note",      "szType":"string", "iLen":12, "szRem":"Note"}, 
  {"szNm":"Gruppi",    "szType":"string", "iLen":8,  "szRem":"Gruppo."},
  {"szNm":"Tag",       "szType":"number", "iLen":4,  "szRem":"Tag."},
  {"fVisible":false,"szNm":"++ Init ++",  "szType":"none", "iLen":0, "szRem":"Init",   "szCode":"$XTG.U_Set_szNote();"},
  {"fVisible":false,"szNm":"szTBM_Table", "szType":"none", "iLen":0, "szRem":"SetPar", "szCode":"XTG"},
  {"fVisible":false,"szNm":"fShow_Icon",  "szType":"none", "iLen":0, "szRem":"SetPar - mostra le icone", "szCode":true},
  {"fVisible":false,"szNm":"iWdt_Image",  "szType":"none", "iLen":0, "szRem":"SetPar - larghezza immagini", "szCode":80},
  {"fVisible":false,"szNm":"jaFld1_aNdx", "szType":"none", "iLen":0, "szRem":"SetPar - sort by field 3 'Modified'", "szCode":3},       // sort in descending order by date (3)
  {"fVisible":false,"szNm":"fAsc",        "szType":"none", "iLen":0, "szRem":"SetPar - seleziona ordine crescente",   "szCode":false}
];

/*----- Module $Type --------------------------------------------------------
*
*/ 
const $Type = (function () {
  var _Type = {};
  _Type.U_Init          = U_Init_Type;        // function U_Init_Type();
  _Type.F_szType        = F_szType;           // function F_szType(P_Val);
  
  _Type.F_asRcd_Type_JS = F_asRcd_Type_JS;    // function F_asRcd_Type_JS(P_szType);
  _Type.F_asRcd_Type    = F_asRcd_Type;       // function F_asRcd_Type(P_szType);
  _Type.F_szType_JS     = F_szType_JS;        // function F_szType_JS(P_szType_Sem);
  _Type.F_szType_Out    = F_szType_Out;       // function F_szType_Out(P_szType_Sem);
  _Type.F_szType_In     = F_szType_In;        // function F_szType_In(P_szType_Sem);
  _Type.F_szType_Anc    = F_szType_Anc;       // function F_szType_Anc(P_szType_Sem);
  _Type.F_fChk_Type     = F_fChk_Type;        // function F_fChk_Type(P_Val, P_szType);
  _Type.F_fChk_Month    = F_fChk_Month;       // function F_fChk_Month(P_Val, P_szType);

  _Type.F_fChk_Week     = F_fChk_Week;        // function F_fChk_Week(P_Val, P_szType);
  _Type.F_Val_Null_Mp_Type  = F_Val_Null_Mp_Type; // function F_Val_Null_Mp_Type(P_szType);
  _Type.U_Set_ims_Sec70_0   = U_Set_ims_Sec70_0;  // function U_Set_ims_Sec70_0(P_ims_Sec70_0); 

  _Type.U_Init_Diagnostic   = U_Init_Diagnostic;  // function U_Init_Diagnostic(P_UsrView);
  _Type.F_szHTML_Diagnostic = F_szHTML_Diagnostic;// function F_szHTML_Diagnostic(P_Item, P_Fld1);

  _Type.U_Conv_Record   = U_Conv_Record;      // function U_Conv_Record();

/*----- Local Constants ----------------------------------------------*/

const C_jCd_Cur = C_jCd_Type;

/*----- Local Variables ----------------------------------------------*/

var S_jaFld1_aNdx = -1;
var S_fFlag = true;        /* Force "Flag" type instead of "boolean". Flag values will be showed as boxes. */
var S_ims_Sec70_0 = 0;     /* Date used in multiple initialization. */

var S_aiCnt_Problem = [0, 0, 0, 0, 0, 0, 0];
var S_iCnt_Problem = 0;
var S_ValPrv;

/*--------------------------------------------------------------------*/

/*-----F_szType --------------------------------------------------------
*
* F_szType() function extends "typeof".
* Return the type of the parameter P_Val
*/ 
function F_szType(P_Val)
{
  var szType = typeof(P_Val);
  var ch;

  switch (szType) {
    case  "string": {
          if (P_Val.length == 10) {     /* Test for date. */
             if (P_Val[2] == P_Val[5]) {
                ch = P_Val[2]; 
             } /* if */
             if (P_Val[4] == P_Val[7]) {
                ch = P_Val[4]; 
             } /* if */
             if ((ch == '-') || (ch == '/') || (ch == '.')) {
                szType = "date";
             } /* if */
          } /* if */
    } break;
    case "boolean": {
          if (S_fFlag) {
             szType = "Flag";
          } /* if */
    } break;
    default : {
    } break;
  } /* switch */

  return(szType);
} /* F_szType */

/*-----F_asRcd_Type_JS --------------------------------------------------------
*
* Return the Type descriptor for the given JavaScript's types 
* otherwise rises an exception.
* $Type.F_asRcd_Type_JS();
*/                                                                   
function F_asRcd_Type_JS(P_szType)
{
  var Type0 = G_asRcd_Type_JS[P_szType];
   if (Type0) {
      return(Type0);
   }
   else {
      $Error.U_Error(C_jCd_Cur, 1, "Unknown Type", P_szType, false);
   } /* if */
} /* F_asRcd_Type_JS */

/*-----F_asRcd_Type --------------------------------------------------------
*
* Return the Type descriptor for the given registered Semantic types 
* otherwise rises an exception.
* $Type.F_asRcd_Type();
*/ 
function F_asRcd_Type(P_szType)
{
  var Type0 = G_asRcd_Type[P_szType];
   if (Type0) {
      return(Type0);
   }
   else {
      $Error.U_Error(C_jCd_Cur, 2, "Unknown Type", P_szType, false);
   } /* if */
} /* F_asRcd_Type */

/*-----F_asRcd_Type_2 --------------------------------------------------------
*
* Return Type descriptor for the given  registered Semantic types.
* otherwise returns a void descriptor.
* $Type.F_asRcd_Type_2();
*/ 
function F_asRcd_Type_2(P_szType)
{
  var Type0 = G_asRcd_Type[P_szType];
   if (Type0) {
      return(Type0);
   }
   else {
      return(null);
   } /* if */
} /* F_asRcd_Type_2 */

/* ----- F_szType_Anc -----------------------------------------------------------
*
* Convert user defined type-names in Basic type-names looking at the ancestors.
* $Type.F_szType_Anc();
*/
function F_szType_Anc(P_szType_Sem) {
  var szType_Anc = "string";    /* set default */
  debugger;
  if (P_szType_Sem in G_asRcd_Type) {
     var Type0 = G_asRcd_Type[P_szType_Sem];
     if (P_szType_Sem != Type0[C_jaType_szType_Anc]) {
        szType_Anc = F_szType_Anc(Type0[C_jaType_szType_Anc]);
     }
     else {
        return(Type0[C_jaType_szType_Anc]);
     } /* if */
  } /* if */

  return(szType_Anc);
} /* F_szType_Anc */

/* ----- F_szType_Out -----------------------------------------------------------
*
* Return the Output type-name corresponding to the given type (P_szType_Sem).
* $Type.F_szType_Out();
*/
function F_szType_Out(P_szType_Sem) {
  var szType_Out = "string";    /* set default */

  if (P_szType_Sem in G_asRcd_Type) {
     var Type0 = G_asRcd_Type[P_szType_Sem];
     szType_Out = Type0[C_jaType_szType_Out];
  } /* if */

  return(szType_Out);
} /* F_szType_Out */

/* ----- F_szType_In -----------------------------------------------------------
*
* Return the Input type-name corresponding to the given type (P_szType_Sem=).
* $Type.F_szType_In();
*/
function F_szType_In(P_szType_Sem) {
  var szType_In = "string";    /* set default */
  debugger;
  if ((P_szType_Sem == "object") || (P_szType_Sem == "Array")){
     szType_In = "object";  // 06/05/2024
     return(szType_In);
  } /* if */

  if (P_szType_Sem in G_asRcd_Type) {
     var Type0 = G_asRcd_Type[P_szType_Sem];
     szType_In = Type0[C_jaType_szType_In];
  } /* if */

  return(szType_In);
} /* F_szType_In */

/* ----- F_szType_JS -----------------------------------------------------------
*
* Return the JavaScript type-name corresponding to the given type (P_szType_Sem=).
* $Type.F_szType_JS();
*/
function F_szType_JS(P_szType_Sem) {
  var szType_JS = "string";    /* set default */

  if ((P_szType_Sem == "object") || (P_szType_Sem == "Array")){
     szType_JS = "object";  // 06/05/2024
     return(szType_JS);
  } /* if */

  if (P_szType_Sem in G_asRcd_Type) {
     var Type0 = G_asRcd_Type[P_szType_Sem];
     szType_JS = Type0[C_jaType_szType_JS];
  } /* if */

  return(szType_JS);
} /* F_szType_JS */

// "Byte":      ["number",   "number",    "number",  8, {"get":"getUInt8",  "CPU":true, "Min":0, "Max":255, "default":0}, "unsigned 8 bits number."],

/*-----F_fChk_Type --------------------------------------------------------
*
* Check value type. Used to check the value entered by the user.
* $Type.F_fChk_Type();
*/ 
function F_fChk_Type(P_Val, P_szTypeReq, P_Fld)
{
  var Aux0 = {};
  var iSyndrome = 0;
  
  if (P_Fld.Aux0) {
     Aux0 = P_Fld.Aux0;
  }
  else {
      var Type0 = F_asRcd_Type_2(P_szTypeReq);
      var szTypeCur = typeof(P_Val);
      var iSyndrome = 0;
      var Aux0;
    
      if (!Type0) {
         /* P_szTypeReq is not a registered type */
         return(true);   /* Accept value under user's responsibility */
      } /* if */
      
      /* registered type */
      
      if (!Type0[C_jaType_oAux]) {
         /* There are no type checking indications for this type go back to its ancestor. */
          if (szTypeCur != Type0[C_jaType_szType_Anc]) {
             return(F_fChk_Type(P_Val, Type0[C_jaType_szType_Anc]));
          }
          else {
             return(true);   /* Accept value under user's responsibility */
          } /* if */  
      } /* if */
    
      Aux0 = Type0[C_jaType_oAux];
  } /* if */
  
  if (Aux0.F_fChk) {
     /* if the user provided a specific check for the values entered use it! */
     iSyndrome |= Aux0.F_fChk(P_Val);
  } /* if */
  
  if (Aux0.Min) {
     if (P_Val < Aux0.Min) {
        iSyndrome |= 1;
     } /* if */
  } /* if */
  if (Aux0.Max) {
     if (Aux0.Max < P_Val) {
        iSyndrome |= 2;
     } /* if */
  } /* if */     
   
  return(iSyndrome != 0);
} /* F_fChk_Type *

/*-----F_szHTML_Diagnostic --------------------------------------------------------
*
* Type-problem "Diagnostic"
* Verify that the value meets the requirements to belong to the domain in question.
* $Type.F_szHTML_Diagnostic(); 
*/ 
function F_szHTML_Diagnostic(P_Val, P_Fld)
{
  var Aux0 = {};
  var szHTML;
  
  if (P_Fld.Aux0) {
     Aux0 = P_Fld.Aux0;
  } /* if */
  
  if (Aux0.F_fChk) {
     /* If the user provided a specific check for the values entered use it! */
     szHTML = "<div class='Cl_HL_1'>" + P_Val + "</div>";    // blue & yellow
     S_iCnt_Problem++;
     S_aiCnt_Problem[0]++;
     return(szHTML);
  } /* if */ 
  if (Aux0.Min) {
     if (P_Val < Aux0.Min) {
       szHTML = "<div class='Cl_HL_2'>" + P_Val + "</div>";  // red & lime
       S_iCnt_Problem++;
       S_aiCnt_Problem[1]++;
       return(szHTML);
     } /* if */
  } /* if */
  if (Aux0.Max) {
     if (Aux0.Max < P_Val) {
       szHTML = "<div class='Cl_HL_3'>" + P_Val + "</div>";  // magenta & cyan
       S_iCnt_Problem++;
       S_aiCnt_Problem[2]++;
       return(szHTML);
     } /* if */
  } /* if */

  let Type0 = F_asRcd_Type(P_Fld.szType);
  let szTypeJS_Req = Type0[C_jaType_szType_JS]; 
  let szType = typeof(P_Val); 
  if (szType != szTypeJS_Req) {
     szHTML = "<div class='Cl_HL_4'>" + P_Val + "</div>";    // yellow & mangenta
     S_iCnt_Problem++;
     S_aiCnt_Problem[3]++;
     return(szHTML);
  } else {
     if (szTypeJS_Req == "number") {
        if (Number.isNaN(P_Val)) {
           szHTML = "<div class='Cl_HL_6'>" + P_Val + "</div>";    // white & red
           S_iCnt_Problem++;
           S_aiCnt_Problem[5]++;
           return(szHTML);
        } /* if */
     } /* if */
  } /* if */
  
  if (P_Fld.iPos1 == S_jaFld1_aNdx) {   // I valori debbono formare una successione crescente!!!
     if (P_Val < S_ValPrv) {
        szHTML = "<div class='Cl_HL_8'>" + P_Val + "</div>"; // red & grey        
        S_ValPrv = P_Val;
        S_iCnt_Problem++;
        S_aiCnt_Problem[4]++;
        return(szHTML);
     } /* if */
     S_ValPrv = P_Val;
  } /* if */
 
  return(P_Val);
} /* F_szHTML_Diagnostic */

/*-----U_Set_ims_Sec70_0 --------------------------------------------------------
*
* Set initial value for multiple date initialization.
*/ 
function U_Set_ims_Sec70_0(P_ims_Sec70_0)
{
  S_ims_Sec70_0 = P_ims_Sec70_0;
} /* U_Set_ims_Sec70_0 */

/*-----F_Val_Null_Mp_Type --------------------------------------------------------
*
* Return a null value of the given type (P_szType).
* $Type.F_Val_Null_Mp_Type();
*/ 
function F_Val_Null_Mp_Type(P_szType)
{
  var Val0;
  switch (P_szType) {
    case "string": {
        Val0 = "";
    } break;
    case "number": {
        Val0 = 0;
    } break;
    case "boolean": {
         Val0 = false;
    } break;
    case "function": {
         Val0 = U_Null;
    } break;
    case "bigint": {
          Val0 = 0n;
    } break;
    case "date": {
          if (S_ims_Sec70_0) {
             S_ims_Sec70_0 += C_ims_Day;
             Val0 = $TimeDate.F_szDate_Mp_ims_Sec70(S_ims_Sec70_0);
          }
          else {
             Val0 = $TimeDate.F_szDate_Now();
          } /* if */
    } break;
    default : {
          Val0 = "";
    } break;
  } /* switch */
  return(Val0);
} /* F_Val_Null_Mp_Type */

/*-----U_Init_Diagnostic --------------------------------------------------------
*
*/ 
function U_Init_Diagnostic(P_UsrView)
{
  if ((P_UsrView.XDB0.JKndTup0 == C_JKndTup_Obj) || (P_UsrView.XDB0.JKndTup0 == C_JKndTup_as_)) {
     S_jaFld1_aNdx = -123;   /* Disable test setting on invalid value. */
     return;
  } /* if */
 
  S_jaFld1_aNdx = P_UsrView.jaFld1;     /* Last column selected */
  
  var Coll0 = P_UsrView.XDB0.Coll0;
  var aNdx = P_UsrView.aNdx;

  if (Coll0 == null) {
     /* The collection has been deallocated, reset aNdx. */
     aNdx = [];
  } /* if */

  if (aNdx.length > 0) {
      let Rcd0 = Coll0[aNdx[0]];
      S_ValPrv = Rcd0[S_jaFld1_aNdx];
  }
  else {
      S_ValPrv = 0;
  } /* if */

  S_aiCnt_Problem = [0, 0, 0, 0, 0];
  S_iCnt_Problem = 0;
} /* U_Init_Diagnostic */

/*-----U_Conv_Record --------------------------------------------------------
*
* Convert record values according to Layout types.
*/ 
function U_Conv_Record()
{
  var UsrView0 = CL_UsrView0.F_UsrView_Selected();
  var XDB0  = UsrView0.XDB0;
  var jaFld = UsrView0.jaFld1;
  var iCard_aFld1 = UsrView0.aFld1.length;
  var aObj0 = [];
  
  for (let i = 0; i < iCard_aFld1; i++) {
      U_Conv_Field0(UsrView0, i); 
  } /* for */

  $Table.U_Display_Table();
} /* U_Conv_Record */

/*-----U_Conv_Field --------------------------------------------------------
*
* Change column values doing type conversion.
*/ 
function U_Conv_Field()
{
  var UsrView0 = CL_UsrView0.F_UsrView_Selected();
  var XDB0  = UsrView0.XDB0;
  var jaFld = UsrView0.jaFld1;
   
  U_Conv_Field0(UsrView0, jaFld);
} /* U_Conv_Field */

/*-----U_Conv_Field0 --------------------------------------------------------
*
*/ 
function U_Conv_Field0(P_UsrView0, P_jaFld)
{
  var XDB0  = P_UsrView0.XDB0;
  var Coll0 = XDB0.Coll0;
  var aFld1 = P_UsrView0.aFld1;
  var szNm;
  var aNdx  = P_UsrView0.aNdx;
  var iCard0 = aNdx.length;
  var Val0;
  var Val1;
  var Fld1;
  var szType0;
  var szType_JS;

  if (XDB0.JKndTup0 != C_JKndTup_aRcd) {
     $Error.U_Error(C_jCd_Cur, 3, "Was expected an array of records.", "", false);  
  } /* if */
  if (P_jaFld < 0) {
     $Error.U_Error(C_jCd_Cur, 4, "No column selected!", "", false);
  } /* if */
  
  Fld1 = aFld1[P_jaFld];
  szNm = Fld1.szNm;
  szType_JS = $Type.F_szType_JS(Fld1.szType);
  
  switch (szType_JS) {
    case "number": {
          for (let i = 0; i < iCard0; i++) {
              Val0 = Coll0[i][P_jaFld];
              szType0 = typeof(Val0);
              if (szType0 == "string") {
                 Val0 = Val0.replace(',', '.');
              } /* if */
              Val0 = +Val0;
              if (!isNaN(Val0)) {
                Coll0[i][P_jaFld] = Val0;        /* Convert in a number */
              } /* if */
          } /* for */
    } break;
    case "string": {
          for (let i = 0; i < iCard0; i++) {
              Val0 = Coll0[i][P_jaFld];
              szType0 = typeof(Val0);
              switch (szType0) {
                case "string": {
                     Coll0[i][P_jaFld] = Val0.trim();
                } break;
                case "undefined": {
                     Coll0[i][P_jaFld] = "";
                } break;
                case "null": {
                     Coll0[i][P_jaFld] = "";
                } break;
                default : {
                      Coll0[i][P_jaFld] = "" + Val0;    /* Convert in a string */
                } break;
              } /* switch */
          } /* for */
    } break;
    case "boolean": {
          for (let i = 0; i < iCard0; i++) {
              Val0 = Coll0[i][P_jaFld];
              szType0 = typeof(Val0);
              switch (szType0) {
                case "boolean" : {
                     Val1 = Val0;                
                } break;
                case "number": {
                     Val1 = !!Val0;  /* Convert in a boolean */
                } break;
                case "string": {
                      Val0 = Val0.toLowerCase();
                      switch (Val0) {
                        case "true":
                        case "TRUE": {
                             Val1 = true;
                        } break;
                        case "false":
                        case "FALSE": {
                             Val1 = false;
                        } break;
                        default : {
                             Val1 = Val0;
                        } break;
                      } /* switch */
                } break;
                case "object" : {
                     Val1 = !!Val0;                
                } break;
                default : {
                } break;
              } /* switch */
              Coll0[i][P_jaFld] = Val1;
          } /* for */
    } break;
    case "date" : {
          for (let i = 0; i < iCard0; i++) {
              Val0 = Coll0[i][P_jaFld];
              Coll0[i][P_jaFld] = F_szConv_Date(Val0, false);
          } /* for */
    } break;
    case "object" : {
  
//         ALERT("object U_Conv_Field0", 1);     22/08/2024
    
    } break;
    case "bigint" : {
          for (let i = 0; i < iCard0; i++) {
              Val0 = Coll0[i][P_jaFld];
              szType0 = typeof(Val0);
              if (szType0 == "undefined") {
                 return;
              } /* if */
              if (szType0 == "string") {
                 Val0 = Val0.replace(',', '.');
              } /* if */
              if (szType0 == "string") {
                 Val0 = Val0.replace('n', '');
              } /* if */
              Val0 = BigInt(Val0);
          } /* for */
    } break;
    case "function" : {
//           for (let i = 0; i < iCard0; i++) {
//               Val0 = Coll0[i][P_jaFld];
//               szType0 = typeof(Val0);
//               if (szType0 == "string") {
//                  try {
//                      Coll0[i][P_jaFld] = eval(Val0);
//                  } catch (P_Err) {
//                  } /* try catch */
//               } /* if */
//           } /* for */    
    } break;
    default : {
    } break;
  } /* switch */
} /* U_Conv_Field0 */

/*-----F_szConv_Date --------------------------------------------------------
*
*/ 
function F_szConv_Date(P_Date, P_fMMDDYYYY)
{
  var szType = typeof(P_Date);
  var szDate;
  
  switch (szType) {
    case "string": {
          if (P_Date.length != 10) {
             /* Not a valid date. */
             return(P_Date);
          } /* if */
          if ((P_Date[4] == '-') && (P_Date[7] == '-')) {     
             return(P_Date);
          }
          else if ((P_Date[2] == '/') && (P_Date[5] == '/')) {
             if (P_fMMDDYYYY) {
                /* MM/DD/YYYY */
                szDate = P_Date.substr(6, 4) + "-" + P_Date.substr(0, 2) + "-" + P_Date.substr(3, 2);
             }
             else {
                szDate = P_Date.substr(6, 4) + "-" + P_Date.substr(3, 2) + "-" + P_Date.substr(0, 2);
             } /* if */
          }
          else {
             return(szDate);
          } /* if */
    } break;
    case "number": {
          /* $Assume it is a timestamp */
          var Date0 = new Date(P_Date);
          var iYear  = Date0.getFullYear();
          var iMonth = Date0.getMonth() +1;
          var iDay   = Date0.getDate();  
          szDate = F_szPad2(iYear) + "-" + F_szPad2(iMonth) + "-" + F_szPad2(iDay);
          return(szDate); 
    } break;
    default : {
    } break;
  } /* switch */
  return(P_Date);
} /* F_szConv_Date */

/*-----U_Init_Type --------------------------------------------------------
*
*/ 
function U_Init_Type()
{
  var i = 0;
  for (let szNm in G_asRcd_Type) {      /* Initialize the list of type-names. */
      G_oEnum_Type[szNm] =  szNm;
      i++;
  } /* for */
  var Aux0 = {"szShow":"list","oEnum":G_oEnum_Type, "iCard":G_oEnum_Type.length};
  G_asRcd_Type["Type"][C_jaType_oAux] = Aux0;
  
  new CL_XDB0(["aFld_aFld",      C_JKndTup_aObj,  G_aFld_aFld,     G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_aFld1",     C_JKndTup_aObj,  G_aFld_aFld1,    G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_Log",       C_JKndTup_aObj,  G_aFld_Log,      G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_Stat",      C_JKndTup_aObj,  G_aFld_Stat,     G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_XDB0",      C_JKndTup_aObj,  G_aFld_XDB0,     G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_UsrView",   C_JKndTup_aObj,  G_aFld_UsrView,  G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);

  new CL_XDB0(["aFld_Obj0",      C_JKndTup_aObj,  G_aFld_Obj0,     G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["New_Layout",     C_JKndTup_aObj,  G_aFld_Obj0,     G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);      /* $NOTE: this is NOT a real layout but a template! */
  new CL_XDB0(["aFld_Year",      C_JKndTup_aObj,  G_aFld_Year,     G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_Calendar",  C_JKndTup_aObj,  G_aFld_Calendar, G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_RcdDay",    C_JKndTup_aObj,  G_aFld_RcdDay,   G_aFld_aFld, "aFld_aFld", "", C_WwFlag_fReadOnly, C_jCd_Cur]);

  new CL_XDB0(["aFld_Type",      C_JKndTup_aObj,  G_aFld_Type,     G_aFld_aFld, "aFld_aFld", "Types Layout.",   C_WwFlag_fReadOnly, C_jCd_Cur]);

  new CL_XDB(["asRcd_Type",      C_JKndTup_asRcd, G_asRcd_Type,    null, "aFld_Type", "Types List.",     (C_WwFlag_fReadOnly | C_WwFlag_fService), C_jCd_Cur, C_Bag_UsrView_Dflt]);
  new CL_XDB(["asRcd_Type_JS",   C_JKndTup_asRcd, G_asRcd_Type_JS, null, "aFld_Type", "JS Types List.",  (C_WwFlag_fReadOnly | C_WwFlag_fService), C_jCd_Cur, C_Bag_UsrView_Dflt]);
  new CL_XDB0(["aFld_Func",      C_JKndTup_aObj,  G_aFld_Func,     G_aFld_aFld, "aFld_aFld", "Function Layout", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_aAbsFreq",  C_JKndTup_aObj,  G_aFld_aAbsFreq, G_aFld_aFld, "aFld_aFld", "Absolute frequencies Layout", C_WwFlag_fReadOnly, C_jCd_Cur]);
  new CL_XDB0(["aFld_FlDsc",     C_JKndTup_aObj,  G_aFld_FlDsc,    G_aFld_aFld, "aFld_aFld", "File Descriptor", C_WwFlag_fReadOnly, C_jCd_Cur]);

  U_Root0("$Type", C_jCd_Cur, 2);
} /* U_Init_Type */

  U_Root0("$Type", C_jCd_Cur, 1);
  return(_Type);
})();  /* Type */

/*-----F_fChk_Month --------------------------------------------------------
* 0123456
* 1999-12
*/ 
function F_fChk_Month(P_Val)
{
  var fRes = (/\d\d\d\d-\d\d/.test(P_Val));
  var iNum = +P_Val.substr(5,2);
  if (fRes && (0<iNum) && (iNum <= 12)) {
     return(0);
  }
  else {
     return(4);
  } /* if */
} /* F_fChk_Month */

/*-----F_fChk_Week --------------------------------------------------------
*
*/ 
function F_fChk_Week(P_Val)
{
  var fRes = (/\d\d\d\d-W\d\d/.test(P_Val));
  var iNum = +P_Val.substr(6,2);
  if (fRes && (0<iNum) && (iNum <= 53)) {
     return(0);
  }
  else {
     return(4);
  } /* if */
} /* F_fChk_Week */
